language: php

# Do not build feature branches or alpha/beta releases
branches:
  only:
    - master
    - develop
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@helhum.io

install:
  - composer require typo3/cms-core $TYPO3_VERSION --no-update
  - composer update

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit tests/Unit/
  - >
    echo;
    echo "Running php lint";
    vendor/bin/parallel-lint --exclude vendor --exclude .Build .

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.4
      env: TYPO3_VERSION="^10.4"
    - stage: test
      php: 7.3
      env: TYPO3_VERSION="^10.4"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="^10.4"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="^9.5"
    - &yaml
      stage: test
      php: 7.3
      env: TYPO3_VERSION="^10.4.1"
      before_install:
        - printf "\n" | pecl install yaml;
    - <<: *yaml
      php: 7.2
