language: php

# Do not build feature branches or alpha/beta releases
branches:
  only:
    - master
    - develop
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@helhum.io

install:
  - composer install

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit tests/Unit/
  - >
    echo;
    echo "Running php lint";
    vendor/bin/parallel-lint --exclude vendor --exclude .Build .

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.3
    - stage: test
      php: 7.2
    - &yaml
      stage: test
      php: 7.3
      env: With yaml extension
      before_install:
        - printf "\n" | pecl install yaml;
    - <<: *yaml
      php: 7.2
